Assign5/Assign5/Models/Child.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Assign5.Models
{
    public class Child
    {
        [Key]
        public int Id { get; set; }
        public string name { get; set; }
        public int age { get; set; }
    }
}

Assign5/Assign5/Models/Departments.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Assign5.Models
{
    public class Departments
    {
        [Key]
        public int dno { get; set; }
        public string dname { get; set; }
        public double budget { get; set; }
    }
}

Assign5/Assign5/Models/Employees.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Assign5.Models
{
    public class Employees
    {

        [Key]
        public string ssn { get; set; }
        public double salary { get; set; }
        public string phone { get; set; }


        public virtual Departments department { get; set; }
        public virtual Child child { get; set; }

    }
}

Assign5/Assign5/Controllers/ChildController.cs
using Assign5.DAL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Assign5.Controllers
{
    public class ChildController : Controller
    {

        private Assign5DBContext db = new Assign5DBContext();


        public ActionResult add(int x = 91, int y = 91)
        {
            ViewData["sum"] = x + y;
            return View();
        }

        public string add1(int x, int y)
        {
            return (x + y).ToString();
        }







        // GET: Child
        public ActionResult Index()
        {
            return View(db.Child.ToList());
        }

        // GET: Child/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Child/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Child/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Child/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Child/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Child/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Child/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Assign5/Assign5/Controllers/DepartmentController.cs
using Assign5.DAL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Assign5.Controllers
{
    public class DepartmentController : Controller
    {

        Assign5DBContext db = new Assign5DBContext();
        // GET: Department
        public ActionResult Index()
        {
            return View(db.Departments.ToList());
        }

        // GET: Department/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Department/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Department/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Department/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Department/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Department/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Department/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Assign5/Assign5/Controllers/EmployeeController.cs
using Assign5.DAL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Assign5.Controllers
{
    public class EmployeeController : Controller
    {

        private Assign5DBContext db = new Assign5DBContext();


        // GET: Employee
        public ActionResult Index()
        {
            return View(db.Employees.ToList());
        }

        
        
        
        
        
        
        // GET: Employee/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Employee/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Employee/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Employee/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Employee/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Employee/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Employee/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Assign5/Assign5/Views/Child/Index.cshtml
@model List<Assign5.Models.Child>

@{
    ViewBag.Title = "Child List";
}

<h2>Index</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.First().name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().age)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.age)
            </td>
            @*<td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.Id })
            </td>*@
        </tr>
    }

</table>

Assign5/Assign5/Views/Child/add.cshtml
@{
    ViewBag.Title = "add";
}

<h1>@ViewData["sum"]</h1>

Assign5/Assign5/Views/Department/Index.cshtml
@model List<Assign5.Models.Departments>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.First().dno)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().dname)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().budget)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.dno)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.dname)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.budget)
            </td>
            @*<td>
                @Html.ActionLink("Edit", "Edit", new { id = item.dno }) |
                @Html.ActionLink("Details", "Details", new { id = item.dno }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.dno })
            </td>*@
        </tr>
    }

</table>

Assign5/Assign5/Views/Employee/Index.cshtml
@model List<Assign5.Models.Employees>

@{
    ViewBag.Title = "Employee List";
}

<h2>Index</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.First().ssn)
        </th>

        <th>
            @Html.DisplayNameFor(model => model.First().salary)
        </th>
        
        <th>
            @Html.DisplayNameFor(model => model.First().phone)
        </th>
        
        <th>
            @Html.DisplayNameFor(model => model.First().child.name)
        </th>
        
        <th>
            @Html.DisplayNameFor(model => model.First().department.dname)
        </th>


        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ssn)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.salary)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.phone)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.child.name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.department.dname)
            </td>

            @*<td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.Id })
            </td>*@
        </tr>
    }

</table>

Assign5/Assign5/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Assign5/Assign5/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Assign5/Assign5/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

Assign5/Assign5/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body class="bg-info">
    <div class="navbar bg-success navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Employee Data", "Index", "Child", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div style="position:absolute; top:20px; right:20px;">
                <ul style="display:flex;width:fit-content;" class="nav">
                    <li>@Html.ActionLink("Child List", "Index", "Child")</li>
                    <li>@Html.ActionLink("Employee List", "Index", "Employee")</li>
                    <li>@Html.ActionLink("Department List", "Index", "Department")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
    </div>



    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>